kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  labels:
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-2
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - affinity
        topologyKey: topology.kubernetes.io/zone

